import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
export default function Chat() {
    const [activeTab, setActiveTab] = useState('friends');
    const [messageText, setMessageText] = useState('');
    const activeChat = {
        name: activeTab === 'friends' ? 'Shroud (Mike)' : 'Sentinels [SEN]',
        status: activeTab === 'friends' ? 'Online' : 'Active Members: 12',
        avatar: activeTab === 'friends' ? 'S' : '🛡️',
    };
    const mockMessages = [
        { id: '1', sender: 'Shroud', content: 'Hey, are you down for Valorant tournaments tonight?', time: '10:04 AM' },
        { id: '2', sender: 'You', content: 'Definitely! I will gather the other clan members.', time: '10:05 AM' },
        { id: '3', sender: 'Shroud', content: 'Awesome, let me know when everyone is ready.', time: '10:06 AM' },
    ];
    return (_jsxs("div", { className: "card glass min-h-[70vh] max-w-6xl mx-auto flex overflow-hidden p-0 border-white/5", children: [_jsxs("div", { className: "w-80 border-r border-white/5 flex flex-col bg-dark-bg/25", children: [_jsxs("div", { className: "flex border-b border-white/5", children: [_jsx("button", { onClick: () => setActiveTab('friends'), className: `flex-1 py-4 text-sm font-semibold tracking-wider transition-colors ${activeTab === 'friends' ? 'text-purple-primary border-b-2 border-purple-primary' : 'text-gray-400 hover:text-white'}`, children: "Friends" }), _jsx("button", { onClick: () => setActiveTab('clans'), className: `flex-1 py-4 text-sm font-semibold tracking-wider transition-colors ${activeTab === 'clans' ? 'text-purple-primary border-b-2 border-purple-primary' : 'text-gray-400 hover:text-white'}`, children: "Clans" })] }), _jsx("div", { className: "flex-grow overflow-y-auto p-4 space-y-2", children: activeTab === 'friends' ? (_jsxs("div", { className: "flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5 cursor-pointer", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-purple-primary/20 flex items-center justify-center font-bold", children: "S" }), _jsxs("div", { className: "flex-grow min-w-0", children: [_jsx("div", { className: "font-semibold text-sm truncate", children: "Shroud" }), _jsx("div", { className: "text-xs text-green-400 truncate", children: "Online" })] })] })) : (_jsxs("div", { className: "flex items-center gap-3 p-3 rounded-lg bg-white/5 border border-white/5 cursor-pointer", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-purple-primary/20 flex items-center justify-center font-bold", children: "\uD83D\uDEE1\uFE0F" }), _jsxs("div", { className: "flex-grow min-w-0", children: [_jsx("div", { className: "font-semibold text-sm truncate", children: "Sentinels [SEN]" }), _jsx("div", { className: "text-xs text-gray-400 truncate", children: "12 Members Online" })] })] })) })] }), _jsxs("div", { className: "flex-grow flex flex-col bg-dark-bg/40", children: [_jsxs("div", { className: "p-4 border-b border-white/5 flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded-full bg-purple-primary/20 flex items-center justify-center font-bold", children: activeChat.avatar }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-sm", children: activeChat.name }), _jsx("span", { className: "text-xs text-gray-400", children: activeChat.status })] })] }), _jsxs("div", { className: "flex-grow p-6 overflow-y-auto space-y-4", children: [_jsx("div", { className: "text-center py-2", children: _jsx("span", { className: "text-[10px] bg-white/5 px-3 py-1 rounded text-gray-500 uppercase tracking-widest font-semibold", children: "Today" }) }), mockMessages.map((msg) => {
                                const isMe = msg.sender === 'You';
                                return (_jsxs("div", { className: `flex flex-col ${isMe ? 'items-end' : 'items-start'}`, children: [_jsx("div", { className: "text-[10px] text-gray-400 mb-1", children: msg.sender }), _jsx("div", { className: `p-3 rounded-lg text-sm max-w-sm ${isMe ? 'bg-purple-primary text-white rounded-tr-none' : 'bg-white/5 text-gray-200 rounded-tl-none'}`, children: msg.content }), _jsx("div", { className: "text-[9px] text-gray-500 mt-1", children: msg.time })] }, msg.id));
                            })] }), _jsx("div", { className: "p-4 border-t border-white/5", children: _jsxs("form", { onSubmit: (e) => { e.preventDefault(); setMessageText(''); }, className: "flex gap-2", children: [_jsx("input", { type: "text", value: messageText, onChange: (e) => setMessageText(e.target.value), className: "flex-grow px-4 py-2.5 bg-dark-bg/60 border border-white/10 rounded-lg focus:outline-none focus:border-purple-primary text-white text-sm", placeholder: "Type your message here..." }), _jsx("button", { type: "submit", className: "btn-primary py-2 px-6 text-sm", children: "Send" })] }) })] })] }));
}
//# sourceMappingURL=Chat.js.map